Resources:
  ProjectKittyCustomers:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      TableName: "ProjectKittyCustomers"
  ProjectKittyAccounts:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "accountNumber"
          AttributeType: "N"
        - AttributeName: "routingNumber"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "accountNumber"
          KeyType: "HASH"
        - AttributeName: "routingNumber"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      TableName: "ProjectKittyAccounts"
  ProjectKittyTransactions:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "accountNumber"
          AttributeType: "N"
        - AttributeName: "submittedDateTime"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "accountNumber"
          KeyType: "HASH"
        - AttributeName: "submittedDateTime"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      TableName: "ProjectKittyTransactions"
  ProjectKittyPeerToPeer:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "sourceCustomerID"
          AttributeType: "N"
        - AttributeName: "destinationCustomerID"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "sourceCustomerID"
          KeyType: "HASH"
        - AttributeName: "destinationCustomerID"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      TableName: "ProjectKittyPeerToPeer"
